apiVersion: v1
kind: Service
metadata:
  name: website-beckend-service
  namespace: website
  labels:
    app: website-beckend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: website-beckend
