apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-beckend-backend
  namespace: website
  labels:
    app: website-beckend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-beckend
  template:
    metadata:
      labels:
        app: website-beckend
    spec:
      containers:
        - name: website-beckend
          image: your-username/website-beckend:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          # If needed, set environment variables, config, etc.
